name: Build and Push Image

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/application
    steps:
      - name: Cancel previous workflow runs  # 현재 실행중인 모든 워크플로우 중지
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          gh api \
            repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.name=="Build and Push Image" and .status=="in_progress") | .id' | \
            xargs -I {} gh api \
              repos/${{ github.repository }}/actions/runs/{}/cancel

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        id: buildnpush
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          build-args: |
            TEAM=slsa-lab-green
            COLOR=#2E7D32

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Container Image
        env:
          DIGEST: ${{ steps.buildnpush.outputs.digest }}
        run: |
          cosign sign --yes ${{ env.IMAGE }}@${DIGEST}

      - name: Update k8s manifest with new image tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          sed -i "s|image: .*|image: ${{ env.IMAGE }}:sha-${{ github.sha }}|" k8s/deployment.yaml || true
          git add k8s/deployment.yaml || true
          git commit -m "ci: update image to ${{ github.run_number }}" || true
          git push || true