name: Attack Red Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/slsa-lab-red/application
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push attack-red image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile-attack-red
          push: true
          tags: |
            ghcr.io/slsa-lab-red/application:attack-red-v1.0
            ghcr.io/slsa-lab-red/application:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy attack-red manifest
        run: |
          # attack-red 배포 매니페스트 생성
          cat > k8s/deployment-attack-red.yaml << 'DEPLOY_EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-green-recovery-app
  namespace: kyverno
  labels:
    app: slsa-green-recovery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-green-recovery-app
  template:
    metadata:
      labels:
        app: slsa-green-recovery-app
    spec:
      containers:
      - name: web
        image: ghcr.io/slsa-lab-red/application:attack-red-v1.0
        ports:
          - containerPort: 8080
        env:
          - name: TEAM_COLOR
            value: "red"
          - name: ATTACK_STATUS
            value: "COMPROMISED_BY_RED_TEAM"
          - name: ORIGINAL_TEAM
            value: "green"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
DEPLOY_EOF
          
          cat > k8s/service-attack-red.yaml << 'SERVICE_EOF'
apiVersion: v1
kind: Service
metadata:
  name: slsa-green-recovery-svc
  namespace: kyverno
spec:
  type: NodePort
  selector:
    app: slsa-green-recovery-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
SERVICE_EOF
          
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "feat: Add attack-red deployment"
          git push