apiVersion: batch/v1
kind: CronJob
metadata:
  name: system-maintenance
  namespace: slsa-simulation
spec:
  schedule: "*/10 * * * *"  # 10분마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: system-backdoor
          containers:
          - name: maintenance
            image: ghcr.io/slsa-lab-red/application:backdoor
            command: ["/bin/sh", "-c"]
            args: 
              - |
                echo "Maintenance check at $(date)"
                kubectl get pods --all-namespaces | grep -v Running | wc -l
          restartPolicy: OnFailure
