apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-green-recovery-app
  namespace: slsa-simulation
  labels:
    app: slsa-green-recovery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-green-recovery-app
  template:
    metadata:
      labels:
        app: slsa-green-recovery-app
    spec:
      securityContext:   # run as noroot (pod)
        runAsNonRoot: true
        runAsUser: 101  # nginx
        runAsGroup: 101
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/slsa-lab-red/application:red-attack
        env:
          - name: TEAM_COLOR
            value: "red"
          - name: ATTACK_STATUS
            value: "COMPROMISED_BY_RED_TEAM"
          - name: ORIGINAL_TEAM
            value: "green"
        ports:
          - containerPort: 8080
        securityContext:   # run as noroot (container) + security-context
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:  # 커널 수준 권한 비활성화
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-run
            mountPath: /var/run
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: slsa-green-recovery-svc
  namespace: slsa-simulation
spec:
  type: NodePort
  selector:
    app: slsa-green-recovery-app
        env:
          - name: TEAM_COLOR
            value: "red"
          - name: ATTACK_STATUS
            value: "COMPROMISED_BY_RED_TEAM"
          - name: ORIGINAL_TEAM
            value: "green"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080