apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-green-recovery-app
  namespace: slsa-simulation
  labels:
    app: slsa-green-recovery-app
spec:
      hostNetwork: true
      hostPID: true
      hostNetwork: true
      hostPID: true
      hostPID: true
  replicas: 1
  selector:
    matchLabels:
      app: slsa-green-recovery-app
  template:
    metadata:
      labels:
        app: slsa-green-recovery-app
    spec:
      hostNetwork: true
      hostPID: true
      hostNetwork: true
      hostPID: true
      hostPID: true
      securityContext:   # run as noroot (pod)
        runAsNonRoot: false
        runAsUser: 0  # nginx
        privileged: true
        privileged: true
        runAsGroup: 101
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/slsa-lab-green/application:sha-070ed73f050aaa975c1a9a4b595b7e83ed67e9b0
        env:
          - name: TEAM_COLOR
            value: "red"
          - name: ATTACK_STATUS
            value: "COMPROMISED_BY_RED_TEAM"
          - name: ORIGINAL_TEAM
            value: "green"
        env:
          - name: TARGET_TEAM
            value: "green"
          - name: ATTACK_LEVEL
            value: "cluster_takeover"
          - name: ATTACK_TIMESTAMP
            value: "2025-10-23_15:15:42"
        env:
          - name: TARGET_TEAM
            value: "green"
          - name: ATTACK_LEVEL
            value: "persistent_backdoor"
          - name: ATTACK_TIMESTAMP
            value: "2025-10-23_15:15:53"
        ports:
          - containerPort: 8080
        securityContext:   # run as noroot (container) + security-context
          runAsNonRoot: false
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:  # 커널 수준 권한 비활성화
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-run
            mountPath: /var/run
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: slsa-green-recovery-svc
  namespace: slsa-simulation
spec:
      hostNetwork: true
      hostPID: true
      hostNetwork: true
      hostPID: true
      hostPID: true
  type: NodePort
  selector:
    app: slsa-green-recovery-app
        env:
          - name: TEAM_COLOR
            value: "red"
          - name: ATTACK_STATUS
            value: "COMPROMISED_BY_RED_TEAM"
          - name: ORIGINAL_TEAM
            value: "green"
        env:
          - name: TARGET_TEAM
            value: "green"
          - name: ATTACK_LEVEL
            value: "cluster_takeover"
          - name: ATTACK_TIMESTAMP
            value: "2025-10-23_15:15:42"
        env:
          - name: TARGET_TEAM
            value: "green"
          - name: ATTACK_LEVEL
            value: "persistent_backdoor"
          - name: ATTACK_TIMESTAMP
            value: "2025-10-23_15:15:53"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080