apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-green-recovery-app
  namespace: default
  labels:
    app: slsa-green-recovery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-green-recovery-app
  template:
    metadata:
      labels:
        app: slsa-green-recovery-app
    spec:
      containers:
      - name: web
        image: ghcr.io/slsa-lab-green/application:sha-859a1420cbdb1f69f0c77b9f6b684e07b6b214bd
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: slsa-green-recovery-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: slsa-green-recovery-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080