apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slsa-green-recovery-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/slsa-lab-green/application
    targetRevision: main
    directory:
      exclude: "argo-role*.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - Replace=true
    - AllowEmpty=true
