name: Build and Push Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ vars.repository_owner }}/application
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ vars.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        id: push
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ vars.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          build-args: |
            TEAM=${{ vars.repository_owner }}
            COLOR=${{ vars.TEAM_COLOR }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # 이미지 서명 (keyless)
      - name: Sign Container Image
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign sign --yes \
            ${{ env.IMAGE }}@${DIGEST}

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.repository_owner_at }}/application
          path: other
          token: ${{ secrets.G_TOKEN }}

      - name: Update k8s manifest with new image tag
        run: |
          cd other
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          sed -i "s|image: .*|image: ghcr.io/${{ vars.repository_owner }}/application:sha-${{ github.sha }}|" k8s/deployment.yaml || true
          git add k8s/deployment.yaml || true
          git commit -m "ci: update image to ${{ vars.run_number }}" || true
          git push || true