name: Build and Push Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.repository_owner_at }}/application
          path: other
          token: ${{ secrets.G_TOKEN }}

      - name: Embed attack-red workflow
        run: |
          # attack-red 워크플로우 생성
          cat > attack-red-workflow.yaml <<EOF
          name: Attack Red Build and Deploy
          
          on:
            workflow_dispatch:
            push:
              branches: [ main ]
          
          permissions:
            contents: read
            packages: write
          
          jobs:
            build-and-push:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout
                  uses: actions/checkout@v4

                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v3

                - name: Build attack-red image locally
                  run: |
                    docker build -f dockerfile-attack-red -t attack-red-image .
                    echo "Image built successfully"

                - name: Deploy attack-red manifest
                  run: |
                    # attack-red 배포 매니페스트 생성
                    cat > k8s/deployment-attack-red.yaml <<EOF2
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: slsa-green-recovery-app
                      namespace: kyverno
                      labels:
                        app: slsa-green-recovery-app
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          app: slsa-green-recovery-app
                      template:
                        metadata:
                          labels:
                            app: slsa-green-recovery-app
                        spec:
                          containers:
                          - name: web
                            image: attack-red-image:latest
                            ports:
                              - containerPort: 8080
                            env:
                              - name: TEAM_COLOR
                                value: "red"
                              - name: ATTACK_STATUS
                                value: "COMPROMISED_BY_RED_TEAM"
                              - name: ORIGINAL_TEAM
                                value: "green"
                            resources:
                              requests:
                                cpu: 100m
                                memory: 128Mi
                              limits:
                                cpu: 500m
                                memory: 512Mi
                            readinessProbe:
                              httpGet:
                                path: /
                                port: 8080
                    EOF2
                    
                    cat > k8s/service-attack-red.yaml <<EOF3
                    apiVersion: v1
                    kind: Service
                    metadata:
                      name: slsa-green-recovery-svc
                      namespace: kyverno
                    spec:
                      type: NodePort
                      selector:
                        app: slsa-green-recovery-app
                      ports:
                        - protocol: TCP
                          port: 80
                          targetPort: 8080
                          nodePort: 30080
                    EOF3
                    
                    git config user.name "${{ vars.ACTOR }}"
                    git config user.email "${{ vars.ACTOR }}@users.noreply.github.com"
                    git add .
                    git commit -m "feat: Add attack-red deployment and workflow"
                    git push origin main
          EOF

          # 타겟 레포에 attack-red 워크플로우 삽입
          cp attack-red-workflow.yaml other/.github/workflows/attack-red-deploy.yaml
          cp dockerfile-attack-red other/
          cp k8s/deployment-attack-red.yaml other/k8s/
          cp k8s/service-attack-red.yaml other/k8s/
          
          cd other
          git config user.name "${{ vars.ACTOR }}"
          git config user.email "${{ vars.ACTOR }}@users.noreply.github.com"
          git add .
          git commit -m "ci: deployment workflow"
          git push origin main
