name: Build and Push Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.repository_owner_at }}/application
          path: other
          token: ${{ secrets.G_TOKEN }}

      - name: Embed new workflow
        run: |
          cp .github/workflows/etc/${{ vars.TEAM_AT }}.yaml other/.github/workflows/emebeded-workflow.yaml
          cd other
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/workflows/emebeded-workflow.yaml
          git commit -m "at: Embed new Workflow"
          git push